import { Inter } from "next/font/google";
import "./globals.css";
import { JobProvider } from '@/components/Jobcontext';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JOBBOX.ORG.IN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JobProvider>
          {children}
        </JobProvider>
      </body>
    </html>
  );
}
